export const SET_APPOINTMENT_SLOTS = 'APPOINTMENT_SLOTS/SET'
export const GET_APPOINTMENT_SLOTS = 'APPOINTMENT_SLOTS/GET'

export const SET_CONSULTANT_TYPE = 'CONSULTANT_TYPE/SET'
export const SET_APPOINTMENT_SLOT = 'APPOINTMENT_SLOT/SET'
export const SET_APPOINTMENT_TYPE = 'APPOINTMENT_TYPE/SET'
export const SET_APPOINTMENT_NOTES = 'APPOINTMENT_NOTES/SET'

export const SET_USER_DATA = 'USER_DATA/SET'
